# Generated by Django 6.0.7 on 2026-07-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_rtsp_url_charfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='snapshot_url',
        ),
        migrations.AddField(
            model_name='alert',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='snapshots/'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('roaming', 'Roaming'), ('exit', 'Exit'), ('unauthorized', 'Unauthorized Entry'), ('motion', 'Motion Detected')], max_length=20),
        ),
    ]
