# Generated by Django 6.0.7 on 2026-07-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_remove_alert_snapshot_url_alert_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('roaming', 'Roaming'), ('exit', 'Exit'), ('unauthorized', 'Unauthorized Entry'), ('motion', 'Motion Detected'), ('recognition', 'Face Recognition')], max_length=20),
        ),
    ]
